### ISSUE TITLE
[Statuttforslag] Definere oppløsning av Motstanden

### ISSUE THREAD

**Issue by Torsteinws** [Motstanden/motstanden-statutter#18]
Det burde statuttfestes hva som skjer hvis Motstanden blir oppløst eller har en periode med ingen medlemmer.
Hva skal for eksempel skje med midlene som er knyttet til Motstandens organisasjonsnummer?

Har ikke konkrete forslag til statuttendringer, ennå.

**Comment by Torsteinws** [comment]
Vedtatt statutt: Dersom  Motstanden oppløses skal midlene fryses og forvaltes av Elektra i 20 år. Etter 20 år kan Elektra gjøre hva de vil med midlene.

**Comment by Torsteinws** [comment]
Styret har ansvar for å sørge for at Elektra er villig til å opprettholde disse vilkårene

**Comment by jorgenrb** [comment]
Nei vwnt

**Comment by jorgenrb** [comment]
Nei vwnt~~~~

**Comment by raflemakt** [comment]
refererer til issue #45
