### ISSUE TITLE
[Statuttforslag] Nettside for hvert styre.

### ISSUE THREAD

**Issue by raflemakt** [Motstanden/motstanden-statutter#19]
Når et nytt styre har blitt valgt inn skal avtroppende webansvarlig lage en ny side på motstanden.no for det nye styret (2022.motstanden.no) som til å begynne med kun inneholder navnene til det nye styret. Det er nå opp til det nye styret hva de vil gjøre med sida si i løpet av det neste året.

**Comment by raflemakt** [comment]
I stedet 2022 som indeks, bruk indeks av styre (som, styre 7 [etter 2018]).

**Comment by Torsteinws** [comment]
Avvises, of flyttes til nettside-repoen

**Comment by Torsteinws** [comment]
Flyttet til nettside-repoen: motstanden/motstanden-website#71
