### ISSUE TITLE
[Statuttforslag] Motstanden trenger en arverekkefølge.

### ISSUE THREAD

**Issue by Hefuglum** [Motstanden/motstanden-statutter#28]
Hvem tar over dersom lederen dør eller ikke kan utføre sine plikter?

**Comment by Torsteinws** [comment]
Avvist, men vi har bestemt å bevare dette dokumentet
[Arv av plasser i motstanden.docx](https://github.com/Motstanden/motstandens-statutter/files/9759197/Arv.av.plasser.i.motstanden.docx)

**Comment by Torsteinws** [comment]
Avvist!

**Comment by Torsteinws** [comment]
Noen som har forslag til hvordan vi skal bevare dette dokumentet?

**Comment by Torsteinws** [comment]
Holder det at issue-et er label-et med "Episk"?

**Comment by jorgenrb** [comment]
Hwlt hinsides, utters episk. Må da gå ann å gjøre

**Comment by raflemakt** [comment]
FØKKINGS KLÅOOSED
