### ISSUE TITLE
[Statuttendring] Koke suppe på fatla 

### ISSUE THREAD

**Issue by SiviKiwi** [Motstanden/motstanden-statutter#31]
Det burde spesifiseres at det er ikke nok å koke suppe på fatla, den må også spises

**Comment by Ninatgun** [comment]
Koket er kun å regne som suppe når suppekokeren inntar suppen.

**Comment by raflemakt** [comment]
MOTSTANDENS generalvro\ralm har stemt over dette og vedtatt forstlaget
