### ISSUE TITLE
[Statuttforslag] Gjør det tydelig at kappen må være ytterst på uniformen

### ISSUE THREAD

**Issue by Torsteinws** [Motstanden/motstanden-statutter#32]
Grunn: Vi har motstanden-medlemmer som går med taktlaus-jakke UTENFOR Motstanden-kappen!

**Comment by Pine-Land** [comment]
Dette er et alvorlig hull

**Comment by jorgenrb** [comment]
Helt krise, kappe ute alltid

**Comment by Ninatgun** [comment]
§ 3.2.4 Som bekledning skal kappen bæres ytterst, og må ikke tildekkes.

**Comment by raflemakt** [comment]
Denne statutten ble diskutert iherdig med ble til slutt nedstemt og ikke vedtatt. Det ble derimot foreslått at vi skal ha biff til middyg.
