### ISSUE TITLE
[Statuttendring] 2 uker er for lenge for innkalling til genvors

### ISSUE THREAD

**Issue by SiviKiwi** [Motstanden/motstanden-statutter#37]
Endre 1.6.2 fra 14 dager til 7. Motstanden har aldri i sitt liv klart å innkalle til noe 2 uker før.

**Comment by Ninatgun** [comment]
§ 6.1.2 Dato for generalvorssamlingen må bli offentliggjort minst 14 dager i forkant.

Til

§ 6.1.2 Dato for generalvorssamlingen må bli offentliggjort minst 10 dager i forkant.

**Comment by jorgenrb** [comment]
Vi sremtec2 ukr

**Comment by raflemakt** [comment]
nedstemt på Motstandens femte foroohming

**Comment by jorgenrb** [comment]
Ki
