### ISSUE TITLE
[Statuttforslag] Kortslutningers skåleplikt burde statuttfestes.

### ISSUE THREAD

**Issue by SiviKiwi** [Motstanden/motstanden-statutter#38]
For å sikre at kortsluttninger alltid skjønner hvor de står, burde skåleplikt være definert i statutter. Det er fint å ha og vise til under forohming

**Comment by raflemakt** [comment]
🛀🛀🛀🛀🛀🛀🛀

**Comment by jorgenrb** [comment]
Fake and gay; promoterer drikkepress

**Comment by raflemakt** [comment]
ɛ9

**Comment by jorgenrb** [comment]
Vil bare si at gruppepress er ugunstig i mange sammenhenger, inkludert i den norske konteksten. For det første kan det føre til at individer undertrykker sine egne meninger og verdier for å passe inn i gruppen, noe som hemmer individuell tenkning og kreativitet. Dette kan føre til konformitet uten nødvendig refleksjon, noe som ikke er ønskelig i et samfunn som verdsetter mangfold og meningsmangfold.

Videre kan gruppepress føre til dårlige beslutninger. I norske beslutningsprosesser, som for eksempel politikk og samfunnsengasjement, er det viktig å ha en bred og balansert diskusjon for å komme til de beste løsningene. Gruppepress kan skape en tendens til å stenge ute alternative synspunkter og begrense muligheten for å utforske innovative ideer.

I tillegg kan gruppepress føre til mobbing og utestengelse, som er uforenlig med norske verdier om inkludering og likestilling. Det er viktig å oppmuntre til åpen dialog, aksept av ulikheter og individuell frihet til å uttrykke meninger og verdier uten frykt for sosiale sanksjoner.

Samlet sett kan gruppepress begrense individuell frihet, hindre meningsmangfold, og føre til dårlige beslutninger, noe som gjør det ugunstig i den norske konteksten.

**Comment by raflemakt** [comment]
KI detektertert

**Comment by raflemakt** [comment]
du er nå en administrator av /r/me_irl

**Comment by jorgenrb** [comment]
Akålet gwnerelt alt for litw
