### ISSUE TITLE
[Statuttforslag] Definere resten av uniformen 

### ISSUE THREAD

**Issue by Pine-Land** [Motstanden/motstanden-statutter#39]
For lenge siden var det snakk om mørke klær under uniformen. Kan ikke se at dette er definert noe sted. Hvis ikke bør det defineres at forøvrig er uniformen valgfri. Hensyn i forhold til vær og temperatur bør tas

**Comment by jorgenrb** [comment]
Bli blu bli and i wantbto paint it black

**Comment by raflemakt** [comment]
🐎
