### ISSUE TITLE
[Statuttforslag] Hvem kan avlegge stemmer på generalforsamlingen

### ISSUE THREAD

**Issue by Pine-Land** [Motstanden/motstanden-statutter#40]
Det står ikke nevnt hvem som kan stemme ved generalforsamlingen? Foreslår at det bare er medlemmer av motstanden som og er medlemmer av Elektra som kan stemme.

**Comment by SiviKiwi** [comment]
Kanskje vi kan ha at alle på genvors har tale- og drikkerett, men det er kun forohmede medlemmer som kan stemme.

**Comment by jorgenrb** [comment]
Stemmer

**Comment by jorgenrb** [comment]
Vil påpeke at å bare gi elektra medle er ganske udemokratisk og lite ønskelig mtp potensielt nye medlemmer

**Comment by raflemakt** [comment]
🦎

**Comment by Ninatgun** [comment]
alle på genvors har tale- og drikkerett, men det er kun forohmede medlemmer og kortslutninger som kan stemme.

**Comment by raflemakt** [comment]
Redigert kommentar fra Ninas forslag (etter diskusjon på genvors):

Alle på genvors har tale- og drikkerett, men det er kun forohmede medlemmer og kortslutninger som kan stemme.

**Comment by raflemakt** [comment]
vedtatt på genvors 2023
