### ISSUE TITLE
[Statuttendring] endre leder 

### ISSUE THREAD

**Issue by SiviKiwi** [Motstanden/motstanden-statutter#41]
Den som styrer motstanden burde ikke være en leder, det er jo det samme som en kortslutting. Før å følge formatet til de andre stillingene kan det kalles prosjektingeniør.
\- Ottar

**Comment by Torsteinws** [comment]
Andre alternativer: Overingeniør, toppingeniør, mesteringeniør, orchesteringeniør, superingeniør, gigaingeniør

**Comment by jorgenrb** [comment]
I helsikke

**Comment by raflemakt** [comment]
Denne issjuen ble i stor grad diskutert på Motstandens femte generalvorsamling og ble avgjort med en avholden stemme for å avgjøre "leder"-stillingen neste år (altså året 2024).
